keep/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo.urls')),
]

todo/urls.py
from django.urls import path
from .import views

app_name='todo'
urlpatterns = [
    path('',views.index,name='index'),
    path('loginUser/',views.loginUser,name='loginUser'),
    path('logoutUser/',views.logoutUser,name='logoutUser'),
    path('createNewUser/',views.createNewUser,name='createNewUser'),
    path('AddTask/',views.AddTask,name='AddTask'),
    path('EditTask/<int:id>/',views.EditTask,name='EditTask'),
    path('DeleteTask/<int:id>/', views.DeleteTask, name='DeleteTask'),
    path('MarkComplete/<int:id>/', views.MarkComplete, name='MarkComplete'),
]

todo/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    title=models.CharField(max_length=50)
    description = models.TextField()
    status=models.BooleanField(default=False)
    datetime = models.DateTimeField(default=datetime.now, blank=True)
    added_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Task
from django.contrib.auth.models import User

class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title','description']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['email', 'username','password']

todo/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import AddTaskForm,UserForm
from .models import Task

@login_required
def index(request):
    tasks=Task.objects.filter(added_by=request.user).order_by('-datetime')
    return render(request,'todo/index.html',{'tasks':tasks})

def loginUser(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('todo:index')
            else:
                return render(request, 'todo/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'todo/login.html', {'error_message': 'Invalid Username or password'})
    else:
        return render(request,'todo/login.html')

@login_required
def logoutUser(request):
    logout(request)
    return redirect('todo:loginUser')

def createNewUser(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            login(request, user)
            return redirect('todo:index')
    else:
        form=UserForm()
        return render(request, 'todo/signup.html', {'form':form})

@login_required
def AddTask(request):
    if request.method=="POST":
        form=AddTaskForm(request.POST)
        if form.is_valid():
            task=form.save(commit=False)
            task.added_by=request.user
            task.save()
            return redirect('todo:index')
    else:
        form=AddTaskForm()
        return render(request,'todo/add_task.html',{'form':form})


@login_required
def EditTask(request,id):
    task = get_object_or_404(Task, pk=id)
    if request.method=="POST":
        form=AddTaskForm(request.POST,instance=task)
        if form.is_valid():
            form.save()
            return redirect('todo:index')
    else:
        form = AddTaskForm(request.POST or None, instance=task)
        return render(request,'todo/add_task.html',{'form':form})

@login_required
def DeleteTask(request,id):
    task=Task.objects.get(pk=id)
    task.delete()
    return redirect('todo:index')

@login_required
def MarkComplete(request,id):
    task=Task.objects.get(pk=id)
    task.status=True
    task.save()
    return redirect('todo:index')

todo/templates/todo/add_task.html
{% extends 'todo/base.html' %}
{% block title %}Add a Task{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="addtaskContainer">
            <h2 class="center">Task</h2>
            <form class="form-group" role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div>
                        <span class="text-danger small">{{ field.errors }}</span>
                    </div>
                    <label>{{ field.label_tag}}</label>
                    <div>{{ field }}</div>
                {% endfor %}
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

todo/templates/todo/base.html
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Akronim|Stylish" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Lato" rel="stylesheet">
    <!--bootstrap css-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "todo/css/style.css" %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'todo:index' %}">ToDo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'todo:AddTask' %}">+ Add a New Task</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#"><span class="badge badge-dark">Hello {{ user }}</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'todo:logoutUser' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>
{% block body %}

{% endblock %}
{% block javascript %}{% endblock %}
<!--bootstrap Js-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/todo/base_visitor.html
<!doctype html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Akronim|Stylish" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Lato" rel="stylesheet">


    <!--bootstrap css-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "todo/css/style.css" %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'todo:index' %}">ToDo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'todo:createNewUser' %}">SignUp</a>
            </li>
        </ul>
    </div>
</nav>
{% block body %}

{% endblock %}
<!--bootstrap Js-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/todo/index.html
{% extends 'todo/base.html' %}
{% block title %}ToDo - A perfect Task Board{% endblock %}
{% block body %}
    <div class="container-fluid p-5">
        <div class="card-columns">
            {% for task in tasks %}
                <div class="card mb-3">
                    <div class="card-header">
                        <span class="task-title">{{ task.title }}</span>
                        {% if task.status is True %}
                            <span class="badge badge-success ml-4">Completed</span>
                        {% else %}
                            <span class="badge badge-warning ml-4">Pending</span>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            {{ task.description|linebreaks}}
                        </p>
                    </div>
                    <div class="card-footer">
                        <a class="card-link" href="{% url 'todo:EditTask' task.id %}">Edit</a>
                        <a class="card-link" href="{% url 'todo:DeleteTask' task.id %}">-Delete</a>
                        {% if task.status is False %}
                            <a class="card-link mc" href="{% url 'todo:MarkComplete' task.id %}">Mark as complete</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

todo/templates/todo/login.html
{% extends 'todo/base_visitor.html' %}
{% block title %}LogIn to your Account{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="loginformContainer">
            <h2 class="center">Log in to your account</h2>
            {% if error_message %}
                <div class="alert alert-danger" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
            <form method="post" action="{% url 'todo:loginUser' %}">
                {% csrf_token %}

                <input type="text" id="username" name="username" placeholder="Your username" required>
                <input type="password" id="password" name="password" placeholder="Your password" required>
                <input type="submit" value="LogIn">
            </form>
            <div class="center">Don't have an account <a href="{% url 'todo:createNewUser' %}">SignUp</a></div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/signup.html
{% extends 'todo/base_visitor.html' %}
{% block title %}Create a new Account{% endblock %}
{% block body %}
    <div class="container">
        <div class="loginformContainer">
            <h2 class="center">Create an Account</h2>
            <form class="form-group" role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        <div>
                            <span class="text-danger small">{{ field.errors }}</span>
                        </div>
                        <label>{{ field.label_tag}}</label>
                        <div>{{ field }}</div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div>
                        <button type="submit">Submit</button>
                    </div>
                </div>
            </form>
            <div class="center">Already have an account <a href="{% url 'todo:loginUser' %}">LogIn</a></div>
        </div>
    </div>
{% endblock %}